In [4]:
##EDA Import

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import importlib

import util_diagnostic
import util_visualization

def reload():
    importlib.reload(util_diagnostic)
    importlib.reload(util_visualization)
file_name = "House_Rent_Dataset.csv"
df = pd.read_csv(file_name)
columns = df.columns
df.head()

Posted On  BHK   Rent  Size            Floor    Area Type  \
0  2022-05-18    2  10000  1100  Ground out of 2   Super Area   
1  2022-05-13    2  20000   800       1 out of 3   Super Area   
2  2022-05-16    2  17000  1000       1 out of 3   Super Area   
3  2022-07-04    2  10000   800       1 out of 2   Super Area   
4  2022-05-09    2   7500   850       1 out of 2  Carpet Area   

              Area Locality     City Furnishing Status  Tenant Preferred  \
0                    Bandel  Kolkata       Unfurnished  Bachelors/Family   
1  Phool Bagan, Kankurgachi  Kolkata    Semi-Furnished  Bachelors/Family   
2   Salt Lake City Sector 2  Kolkata    Semi-Furnished  Bachelors/Family   
3               Dumdum Park  Kolkata       Unfurnished  Bachelors/Family   
4             South Dum Dum  Kolkata       Unfurnished         Bachelors   

   Bathroom Point of Contact  
0         2    Contact Owner  
1         1    Contact Owner  
2         1    Contact Owner  
3         1    Contact Owner  
4         1    Contact Owner

In [15]:
reload()
util_diagnostic.getTotalUniqueColumns(df, df.columns, True )

Column : Posted On, 81
['2022-05-18' '2022-05-13' '2022-05-16' '2022-07-04' '2022-05-09'
 '2022-04-29' '2022-06-21' '2022-06-07' '2022-06-20' '2022-05-23'] object


Column : BHK, 6
[2 1 3 6 4 5] int64


Column : Rent, 243
[10000 20000 17000  7500  7000  5000 26000 25000  6500  5500] int64


Column : Size, 615
[1100  800 1000  850  600  700  250 1200  400  375] int64


Column : Floor, 480
['Ground out of 2' '1 out of 3' '1 out of 2' 'Ground out of 1'
 'Ground out of 4' '1 out of 4' '1 out of 1' 'Ground out of 3'
 '2 out of 3' '4 out of 5'] object


Column : Area Type, 3
['Super Area' 'Carpet Area' 'Built Area'] object


Column : Area Locality, 2235
['Bandel' 'Phool Bagan, Kankurgachi' 'Salt Lake City Sector 2'
 'Dumdum Park' 'South Dum Dum' 'Thakurpukur' 'Malancha'
 'Palm Avenue Kolkata, Ballygunge' 'Natunhat'
 'Action Area 1, Rajarhat Newtown'] object


Column : City, 6
['Kolkata' 'Mumbai' 'Bangalore' 'Delhi' 'Chennai' 'Hyderabad'] object


Column : Furnishing Status, 3
['Unfurnished' 

In [16]:
df.describe()

BHK          Rent         Size     Bathroom
count  4746.000000  4.746000e+03  4746.000000  4746.000000
mean      2.083860  3.499345e+04   967.490729     1.965866
std       0.832256  7.810641e+04   634.202328     0.884532
min       1.000000  1.200000e+03    10.000000     1.000000
25%       2.000000  1.000000e+04   550.000000     1.000000
50%       2.000000  1.600000e+04   850.000000     2.000000
75%       3.000000  3.300000e+04  1200.000000     2.000000
max       6.000000  3.500000e+06  8000.000000    10.000000